// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Category struct {
	ID          int32  `json:"id"`
	Slug        string `json:"slug"`
	Name        string `json:"name"`
	Accent      string `json:"accent"`
	Description string `json:"description"`
}

type Entry struct {
	ID              int32         `json:"id"`
	CategoryID      int32         `json:"category_id"`
	EntryType       string        `json:"entry_type"`
	Title           string        `json:"title"`
	Slug            string        `json:"slug"`
	Excerpt         string        `json:"excerpt"`
	ContentMarkdown string        `json:"content_markdown"`
	CoverMediaID    sql.NullInt32 `json:"cover_media_id"`
	Published       bool          `json:"published"`
	IsPrivate       bool          `json:"is_private"`
	EntryNumber     int32         `json:"entry_number"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
}

type EntryVersion struct {
	ID                int32                 `json:"id"`
	EntryID           int32                 `json:"entry_id"`
	VersionNumber     int32                 `json:"version_number"`
	Title             string                `json:"title"`
	Excerpt           string                `json:"excerpt"`
	ContentMarkdown   string                `json:"content_markdown"`
	EntryType         string                `json:"entry_type"`
	CategoryID        int32                 `json:"category_id"`
	RecipeServings    sql.NullInt32         `json:"recipe_servings"`
	RecipePrepMinutes sql.NullInt32         `json:"recipe_prep_minutes"`
	RecipeCookMinutes sql.NullInt32         `json:"recipe_cook_minutes"`
	RecipeIngredients pqtype.NullRawMessage `json:"recipe_ingredients"`
	RecipeSteps       pqtype.NullRawMessage `json:"recipe_steps"`
	Message           string                `json:"message"`
	CreatedAt         time.Time             `json:"created_at"`
}

type Medium struct {
	ID         int32         `json:"id"`
	EntryID    sql.NullInt32 `json:"entry_id"`
	Filename   string        `json:"filename"`
	Filepath   string        `json:"filepath"`
	Kind       string        `json:"kind"`
	MimeType   string        `json:"mime_type"`
	UploadedAt time.Time     `json:"uploaded_at"`
}

type RecipeDetail struct {
	ID          int32           `json:"id"`
	EntryID     int32           `json:"entry_id"`
	Servings    int32           `json:"servings"`
	PrepMinutes int32           `json:"prep_minutes"`
	CookMinutes int32           `json:"cook_minutes"`
	Ingredients json.RawMessage `json:"ingredients"`
	Steps       json.RawMessage `json:"steps"`
}

type User struct {
	ID             int32     `json:"id"`
	Username       string    `json:"username"`
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
}
