// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const countEntries = `-- name: CountEntries :one
SELECT count(*) FROM entries
`

func (q *Queries) CountEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEntriesInCategory = `-- name: CountEntriesInCategory :one
SELECT count(*) FROM entries WHERE category_id = $1
`

func (q *Queries) CountEntriesInCategory(ctx context.Context, categoryID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEntriesInCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (slug, name, accent, description)
VALUES ($1, $2, $3, $4)
RETURNING id, slug, name, accent, description
`

type CreateCategoryParams struct {
	Slug        string `json:"slug"`
	Name        string `json:"name"`
	Accent      string `json:"accent"`
	Description string `json:"description"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.Slug,
		arg.Name,
		arg.Accent,
		arg.Description,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Accent,
		&i.Description,
	)
	return i, err
}

const createCategoryIfMissing = `-- name: CreateCategoryIfMissing :exec
INSERT INTO categories (slug, name, accent, description)
VALUES ($1, $2, $3, $4)
ON CONFLICT (slug) DO NOTHING
`

type CreateCategoryIfMissingParams struct {
	Slug        string `json:"slug"`
	Name        string `json:"name"`
	Accent      string `json:"accent"`
	Description string `json:"description"`
}

func (q *Queries) CreateCategoryIfMissing(ctx context.Context, arg CreateCategoryIfMissingParams) error {
	_, err := q.db.ExecContext(ctx, createCategoryIfMissing,
		arg.Slug,
		arg.Name,
		arg.Accent,
		arg.Description,
	)
	return err
}

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (category_id, entry_type, title, slug, excerpt, content_markdown, published, is_private, entry_number)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, category_id, entry_type, title, slug, excerpt, content_markdown, cover_media_id, published, is_private, entry_number, created_at, updated_at
`

type CreateEntryParams struct {
	CategoryID      int32  `json:"category_id"`
	EntryType       string `json:"entry_type"`
	Title           string `json:"title"`
	Slug            string `json:"slug"`
	Excerpt         string `json:"excerpt"`
	ContentMarkdown string `json:"content_markdown"`
	Published       bool   `json:"published"`
	IsPrivate       bool   `json:"is_private"`
	EntryNumber     int32  `json:"entry_number"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry,
		arg.CategoryID,
		arg.EntryType,
		arg.Title,
		arg.Slug,
		arg.Excerpt,
		arg.ContentMarkdown,
		arg.Published,
		arg.IsPrivate,
		arg.EntryNumber,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.EntryType,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.ContentMarkdown,
		&i.CoverMediaID,
		&i.Published,
		&i.IsPrivate,
		&i.EntryNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEntryVersion = `-- name: CreateEntryVersion :one
INSERT INTO entry_versions (
    entry_id, version_number, title, excerpt, content_markdown, entry_type, category_id,
    recipe_servings, recipe_prep_minutes, recipe_cook_minutes, recipe_ingredients, recipe_steps, message
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, entry_id, version_number, title, excerpt, content_markdown, entry_type, category_id, recipe_servings, recipe_prep_minutes, recipe_cook_minutes, recipe_ingredients, recipe_steps, message, created_at
`

type CreateEntryVersionParams struct {
	EntryID           int32                 `json:"entry_id"`
	VersionNumber     int32                 `json:"version_number"`
	Title             string                `json:"title"`
	Excerpt           string                `json:"excerpt"`
	ContentMarkdown   string                `json:"content_markdown"`
	EntryType         string                `json:"entry_type"`
	CategoryID        int32                 `json:"category_id"`
	RecipeServings    sql.NullInt32         `json:"recipe_servings"`
	RecipePrepMinutes sql.NullInt32         `json:"recipe_prep_minutes"`
	RecipeCookMinutes sql.NullInt32         `json:"recipe_cook_minutes"`
	RecipeIngredients pqtype.NullRawMessage `json:"recipe_ingredients"`
	RecipeSteps       pqtype.NullRawMessage `json:"recipe_steps"`
	Message           string                `json:"message"`
}

func (q *Queries) CreateEntryVersion(ctx context.Context, arg CreateEntryVersionParams) (EntryVersion, error) {
	row := q.db.QueryRowContext(ctx, createEntryVersion,
		arg.EntryID,
		arg.VersionNumber,
		arg.Title,
		arg.Excerpt,
		arg.ContentMarkdown,
		arg.EntryType,
		arg.CategoryID,
		arg.RecipeServings,
		arg.RecipePrepMinutes,
		arg.RecipeCookMinutes,
		arg.RecipeIngredients,
		arg.RecipeSteps,
		arg.Message,
	)
	var i EntryVersion
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.VersionNumber,
		&i.Title,
		&i.Excerpt,
		&i.ContentMarkdown,
		&i.EntryType,
		&i.CategoryID,
		&i.RecipeServings,
		&i.RecipePrepMinutes,
		&i.RecipeCookMinutes,
		&i.RecipeIngredients,
		&i.RecipeSteps,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (entry_id, filename, filepath, kind, mime_type)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, entry_id, filename, filepath, kind, mime_type, uploaded_at
`

type CreateMediaParams struct {
	EntryID  sql.NullInt32 `json:"entry_id"`
	Filename string        `json:"filename"`
	Filepath string        `json:"filepath"`
	Kind     string        `json:"kind"`
	MimeType string        `json:"mime_type"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRowContext(ctx, createMedia,
		arg.EntryID,
		arg.Filename,
		arg.Filepath,
		arg.Kind,
		arg.MimeType,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.Filename,
		&i.Filepath,
		&i.Kind,
		&i.MimeType,
		&i.UploadedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, hashed_password) VALUES ($1, $2)
ON CONFLICT (username) DO NOTHING
RETURNING id, username, hashed_password, created_at
`

type CreateUserParams struct {
	Username       string `json:"username"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM entries WHERE id = $1
`

func (q *Queries) DeleteEntry(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteEntry, id)
	return err
}

const deleteMediaByEntry = `-- name: DeleteMediaByEntry :exec
DELETE FROM media WHERE entry_id = $1
`

func (q *Queries) DeleteMediaByEntry(ctx context.Context, entryID sql.NullInt32) error {
	_, err := q.db.ExecContext(ctx, deleteMediaByEntry, entryID)
	return err
}

const deleteRecipeDetail = `-- name: DeleteRecipeDetail :exec
DELETE FROM recipe_details WHERE entry_id = $1
`

func (q *Queries) DeleteRecipeDetail(ctx context.Context, entryID int32) error {
	_, err := q.db.ExecContext(ctx, deleteRecipeDetail, entryID)
	return err
}

const entrySlugExists = `-- name: EntrySlugExists :one
SELECT EXISTS(SELECT 1 FROM entries WHERE slug = $1)
`

func (q *Queries) EntrySlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRowContext(ctx, entrySlugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, slug, name, accent, description FROM categories WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id int32) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Accent,
		&i.Description,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, slug, name, accent, description FROM categories WHERE slug = $1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Accent,
		&i.Description,
	)
	return i, err
}

const getEntryByID = `-- name: GetEntryByID :one
SELECT e.id, e.category_id, e.entry_type, e.title, e.slug, e.excerpt, e.content_markdown, e.cover_media_id, e.published, e.is_private, e.entry_number, e.created_at, e.updated_at, c.slug AS category_slug, c.name AS category_name, c.accent AS category_accent
FROM entries e
JOIN categories c ON c.id = e.category_id
WHERE e.id = $1
`

type GetEntryByIDRow struct {
	ID              int32         `json:"id"`
	CategoryID      int32         `json:"category_id"`
	EntryType       string        `json:"entry_type"`
	Title           string        `json:"title"`
	Slug            string        `json:"slug"`
	Excerpt         string        `json:"excerpt"`
	ContentMarkdown string        `json:"content_markdown"`
	CoverMediaID    sql.NullInt32 `json:"cover_media_id"`
	Published       bool          `json:"published"`
	IsPrivate       bool          `json:"is_private"`
	EntryNumber     int32         `json:"entry_number"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
	CategorySlug    string        `json:"category_slug"`
	CategoryName    string        `json:"category_name"`
	CategoryAccent  string        `json:"category_accent"`
}

func (q *Queries) GetEntryByID(ctx context.Context, id int32) (GetEntryByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getEntryByID, id)
	var i GetEntryByIDRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.EntryType,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.ContentMarkdown,
		&i.CoverMediaID,
		&i.Published,
		&i.IsPrivate,
		&i.EntryNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategorySlug,
		&i.CategoryName,
		&i.CategoryAccent,
	)
	return i, err
}

const getEntryBySlug = `-- name: GetEntryBySlug :one
SELECT e.id, e.category_id, e.entry_type, e.title, e.slug, e.excerpt, e.content_markdown, e.cover_media_id, e.published, e.is_private, e.entry_number, e.created_at, e.updated_at, c.slug AS category_slug, c.name AS category_name, c.accent AS category_accent
FROM entries e
JOIN categories c ON c.id = e.category_id
WHERE e.slug = $1
`

type GetEntryBySlugRow struct {
	ID              int32         `json:"id"`
	CategoryID      int32         `json:"category_id"`
	EntryType       string        `json:"entry_type"`
	Title           string        `json:"title"`
	Slug            string        `json:"slug"`
	Excerpt         string        `json:"excerpt"`
	ContentMarkdown string        `json:"content_markdown"`
	CoverMediaID    sql.NullInt32 `json:"cover_media_id"`
	Published       bool          `json:"published"`
	IsPrivate       bool          `json:"is_private"`
	EntryNumber     int32         `json:"entry_number"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
	CategorySlug    string        `json:"category_slug"`
	CategoryName    string        `json:"category_name"`
	CategoryAccent  string        `json:"category_accent"`
}

func (q *Queries) GetEntryBySlug(ctx context.Context, slug string) (GetEntryBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getEntryBySlug, slug)
	var i GetEntryBySlugRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.EntryType,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.ContentMarkdown,
		&i.CoverMediaID,
		&i.Published,
		&i.IsPrivate,
		&i.EntryNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategorySlug,
		&i.CategoryName,
		&i.CategoryAccent,
	)
	return i, err
}

const getEntryVersion = `-- name: GetEntryVersion :one
SELECT id, entry_id, version_number, title, excerpt, content_markdown, entry_type, category_id, recipe_servings, recipe_prep_minutes, recipe_cook_minutes, recipe_ingredients, recipe_steps, message, created_at FROM entry_versions WHERE entry_id = $1 AND version_number = $2
`

type GetEntryVersionParams struct {
	EntryID       int32 `json:"entry_id"`
	VersionNumber int32 `json:"version_number"`
}

func (q *Queries) GetEntryVersion(ctx context.Context, arg GetEntryVersionParams) (EntryVersion, error) {
	row := q.db.QueryRowContext(ctx, getEntryVersion, arg.EntryID, arg.VersionNumber)
	var i EntryVersion
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.VersionNumber,
		&i.Title,
		&i.Excerpt,
		&i.ContentMarkdown,
		&i.EntryType,
		&i.CategoryID,
		&i.RecipeServings,
		&i.RecipePrepMinutes,
		&i.RecipeCookMinutes,
		&i.RecipeIngredients,
		&i.RecipeSteps,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestVersionNumber = `-- name: GetLatestVersionNumber :one
SELECT COALESCE(MAX(version_number), 0)::int FROM entry_versions WHERE entry_id = $1
`

func (q *Queries) GetLatestVersionNumber(ctx context.Context, entryID int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getLatestVersionNumber, entryID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getRecipeDetail = `-- name: GetRecipeDetail :one
SELECT id, entry_id, servings, prep_minutes, cook_minutes, ingredients, steps FROM recipe_details WHERE entry_id = $1
`

func (q *Queries) GetRecipeDetail(ctx context.Context, entryID int32) (RecipeDetail, error) {
	row := q.db.QueryRowContext(ctx, getRecipeDetail, entryID)
	var i RecipeDetail
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.Servings,
		&i.PrepMinutes,
		&i.CookMinutes,
		&i.Ingredients,
		&i.Steps,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, hashed_password, created_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.CreatedAt,
	)
	return i, err
}

const listAllEntries = `-- name: ListAllEntries :many
SELECT e.id, e.category_id, e.entry_type, e.title, e.slug, e.excerpt, e.content_markdown, e.cover_media_id, e.published, e.is_private, e.entry_number, e.created_at, e.updated_at, c.slug AS category_slug, c.name AS category_name, c.accent AS category_accent
FROM entries e
JOIN categories c ON c.id = e.category_id
ORDER BY e.created_at DESC
`

type ListAllEntriesRow struct {
	ID              int32         `json:"id"`
	CategoryID      int32         `json:"category_id"`
	EntryType       string        `json:"entry_type"`
	Title           string        `json:"title"`
	Slug            string        `json:"slug"`
	Excerpt         string        `json:"excerpt"`
	ContentMarkdown string        `json:"content_markdown"`
	CoverMediaID    sql.NullInt32 `json:"cover_media_id"`
	Published       bool          `json:"published"`
	IsPrivate       bool          `json:"is_private"`
	EntryNumber     int32         `json:"entry_number"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
	CategorySlug    string        `json:"category_slug"`
	CategoryName    string        `json:"category_name"`
	CategoryAccent  string        `json:"category_accent"`
}

func (q *Queries) ListAllEntries(ctx context.Context) ([]ListAllEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllEntriesRow
	for rows.Next() {
		var i ListAllEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.EntryType,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.ContentMarkdown,
			&i.CoverMediaID,
			&i.Published,
			&i.IsPrivate,
			&i.EntryNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategorySlug,
			&i.CategoryName,
			&i.CategoryAccent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, slug, name, accent, description FROM categories ORDER BY id
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Accent,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByCategoryAnyVisibility = `-- name: ListEntriesByCategoryAnyVisibility :many
SELECT e.id, e.category_id, e.entry_type, e.title, e.slug, e.excerpt, e.content_markdown, e.cover_media_id, e.published, e.is_private, e.entry_number, e.created_at, e.updated_at, c.slug AS category_slug, c.name AS category_name, c.accent AS category_accent
FROM entries e
JOIN categories c ON c.id = e.category_id
WHERE c.slug = $1 AND e.published = true
ORDER BY e.created_at DESC
`

type ListEntriesByCategoryAnyVisibilityRow struct {
	ID              int32         `json:"id"`
	CategoryID      int32         `json:"category_id"`
	EntryType       string        `json:"entry_type"`
	Title           string        `json:"title"`
	Slug            string        `json:"slug"`
	Excerpt         string        `json:"excerpt"`
	ContentMarkdown string        `json:"content_markdown"`
	CoverMediaID    sql.NullInt32 `json:"cover_media_id"`
	Published       bool          `json:"published"`
	IsPrivate       bool          `json:"is_private"`
	EntryNumber     int32         `json:"entry_number"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
	CategorySlug    string        `json:"category_slug"`
	CategoryName    string        `json:"category_name"`
	CategoryAccent  string        `json:"category_accent"`
}

func (q *Queries) ListEntriesByCategoryAnyVisibility(ctx context.Context, slug string) ([]ListEntriesByCategoryAnyVisibilityRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesByCategoryAnyVisibility, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesByCategoryAnyVisibilityRow
	for rows.Next() {
		var i ListEntriesByCategoryAnyVisibilityRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.EntryType,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.ContentMarkdown,
			&i.CoverMediaID,
			&i.Published,
			&i.IsPrivate,
			&i.EntryNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategorySlug,
			&i.CategoryName,
			&i.CategoryAccent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByCategoryPublic = `-- name: ListEntriesByCategoryPublic :many
SELECT e.id, e.category_id, e.entry_type, e.title, e.slug, e.excerpt, e.content_markdown, e.cover_media_id, e.published, e.is_private, e.entry_number, e.created_at, e.updated_at, c.slug AS category_slug, c.name AS category_name, c.accent AS category_accent
FROM entries e
JOIN categories c ON c.id = e.category_id
WHERE c.slug = $1 AND e.published = true AND e.is_private = false
ORDER BY e.created_at DESC
`

type ListEntriesByCategoryPublicRow struct {
	ID              int32         `json:"id"`
	CategoryID      int32         `json:"category_id"`
	EntryType       string        `json:"entry_type"`
	Title           string        `json:"title"`
	Slug            string        `json:"slug"`
	Excerpt         string        `json:"excerpt"`
	ContentMarkdown string        `json:"content_markdown"`
	CoverMediaID    sql.NullInt32 `json:"cover_media_id"`
	Published       bool          `json:"published"`
	IsPrivate       bool          `json:"is_private"`
	EntryNumber     int32         `json:"entry_number"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
	CategorySlug    string        `json:"category_slug"`
	CategoryName    string        `json:"category_name"`
	CategoryAccent  string        `json:"category_accent"`
}

func (q *Queries) ListEntriesByCategoryPublic(ctx context.Context, slug string) ([]ListEntriesByCategoryPublicRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesByCategoryPublic, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesByCategoryPublicRow
	for rows.Next() {
		var i ListEntriesByCategoryPublicRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.EntryType,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.ContentMarkdown,
			&i.CoverMediaID,
			&i.Published,
			&i.IsPrivate,
			&i.EntryNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategorySlug,
			&i.CategoryName,
			&i.CategoryAccent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntryVersions = `-- name: ListEntryVersions :many
SELECT id, entry_id, version_number, title, excerpt, content_markdown, entry_type, category_id, recipe_servings, recipe_prep_minutes, recipe_cook_minutes, recipe_ingredients, recipe_steps, message, created_at FROM entry_versions WHERE entry_id = $1 ORDER BY version_number DESC
`

func (q *Queries) ListEntryVersions(ctx context.Context, entryID int32) ([]EntryVersion, error) {
	rows, err := q.db.QueryContext(ctx, listEntryVersions, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntryVersion
	for rows.Next() {
		var i EntryVersion
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.VersionNumber,
			&i.Title,
			&i.Excerpt,
			&i.ContentMarkdown,
			&i.EntryType,
			&i.CategoryID,
			&i.RecipeServings,
			&i.RecipePrepMinutes,
			&i.RecipeCookMinutes,
			&i.RecipeIngredients,
			&i.RecipeSteps,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestAnyVisibilityEntries = `-- name: ListLatestAnyVisibilityEntries :many
SELECT e.id, e.category_id, e.entry_type, e.title, e.slug, e.excerpt, e.content_markdown, e.cover_media_id, e.published, e.is_private, e.entry_number, e.created_at, e.updated_at, c.slug AS category_slug, c.name AS category_name, c.accent AS category_accent
FROM entries e
JOIN categories c ON c.id = e.category_id
WHERE e.published = true
ORDER BY e.created_at DESC
LIMIT $1
`

type ListLatestAnyVisibilityEntriesRow struct {
	ID              int32         `json:"id"`
	CategoryID      int32         `json:"category_id"`
	EntryType       string        `json:"entry_type"`
	Title           string        `json:"title"`
	Slug            string        `json:"slug"`
	Excerpt         string        `json:"excerpt"`
	ContentMarkdown string        `json:"content_markdown"`
	CoverMediaID    sql.NullInt32 `json:"cover_media_id"`
	Published       bool          `json:"published"`
	IsPrivate       bool          `json:"is_private"`
	EntryNumber     int32         `json:"entry_number"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
	CategorySlug    string        `json:"category_slug"`
	CategoryName    string        `json:"category_name"`
	CategoryAccent  string        `json:"category_accent"`
}

func (q *Queries) ListLatestAnyVisibilityEntries(ctx context.Context, limit int32) ([]ListLatestAnyVisibilityEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listLatestAnyVisibilityEntries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestAnyVisibilityEntriesRow
	for rows.Next() {
		var i ListLatestAnyVisibilityEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.EntryType,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.ContentMarkdown,
			&i.CoverMediaID,
			&i.Published,
			&i.IsPrivate,
			&i.EntryNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategorySlug,
			&i.CategoryName,
			&i.CategoryAccent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestPublicEntries = `-- name: ListLatestPublicEntries :many
SELECT e.id, e.category_id, e.entry_type, e.title, e.slug, e.excerpt, e.content_markdown, e.cover_media_id, e.published, e.is_private, e.entry_number, e.created_at, e.updated_at, c.slug AS category_slug, c.name AS category_name, c.accent AS category_accent
FROM entries e
JOIN categories c ON c.id = e.category_id
WHERE e.published = true AND e.is_private = false
ORDER BY e.created_at DESC
LIMIT $1
`

type ListLatestPublicEntriesRow struct {
	ID              int32         `json:"id"`
	CategoryID      int32         `json:"category_id"`
	EntryType       string        `json:"entry_type"`
	Title           string        `json:"title"`
	Slug            string        `json:"slug"`
	Excerpt         string        `json:"excerpt"`
	ContentMarkdown string        `json:"content_markdown"`
	CoverMediaID    sql.NullInt32 `json:"cover_media_id"`
	Published       bool          `json:"published"`
	IsPrivate       bool          `json:"is_private"`
	EntryNumber     int32         `json:"entry_number"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
	CategorySlug    string        `json:"category_slug"`
	CategoryName    string        `json:"category_name"`
	CategoryAccent  string        `json:"category_accent"`
}

func (q *Queries) ListLatestPublicEntries(ctx context.Context, limit int32) ([]ListLatestPublicEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listLatestPublicEntries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestPublicEntriesRow
	for rows.Next() {
		var i ListLatestPublicEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.EntryType,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.ContentMarkdown,
			&i.CoverMediaID,
			&i.Published,
			&i.IsPrivate,
			&i.EntryNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategorySlug,
			&i.CategoryName,
			&i.CategoryAccent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaByEntry = `-- name: ListMediaByEntry :many
SELECT id, entry_id, filename, filepath, kind, mime_type, uploaded_at FROM media WHERE entry_id = $1 ORDER BY id
`

func (q *Queries) ListMediaByEntry(ctx context.Context, entryID sql.NullInt32) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, listMediaByEntry, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.Filename,
			&i.Filepath,
			&i.Kind,
			&i.MimeType,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEntryCover = `-- name: SetEntryCover :exec
UPDATE entries SET cover_media_id = $2 WHERE id = $1
`

type SetEntryCoverParams struct {
	ID           int32         `json:"id"`
	CoverMediaID sql.NullInt32 `json:"cover_media_id"`
}

func (q *Queries) SetEntryCover(ctx context.Context, arg SetEntryCoverParams) error {
	_, err := q.db.ExecContext(ctx, setEntryCover, arg.ID, arg.CoverMediaID)
	return err
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE categories SET name = $2, description = $3, accent = $4 WHERE id = $1
`

type UpdateCategoryParams struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Accent      string `json:"accent"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Accent,
	)
	return err
}

const updateEntry = `-- name: UpdateEntry :exec
UPDATE entries
SET category_id = $2, entry_type = $3, title = $4, excerpt = $5,
    content_markdown = $6, published = $7, is_private = $8, updated_at = now()
WHERE id = $1
`

type UpdateEntryParams struct {
	ID              int32  `json:"id"`
	CategoryID      int32  `json:"category_id"`
	EntryType       string `json:"entry_type"`
	Title           string `json:"title"`
	Excerpt         string `json:"excerpt"`
	ContentMarkdown string `json:"content_markdown"`
	Published       bool   `json:"published"`
	IsPrivate       bool   `json:"is_private"`
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) error {
	_, err := q.db.ExecContext(ctx, updateEntry,
		arg.ID,
		arg.CategoryID,
		arg.EntryType,
		arg.Title,
		arg.Excerpt,
		arg.ContentMarkdown,
		arg.Published,
		arg.IsPrivate,
	)
	return err
}

const upsertRecipeDetail = `-- name: UpsertRecipeDetail :exec
INSERT INTO recipe_details (entry_id, servings, prep_minutes, cook_minutes, ingredients, steps)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (entry_id) DO UPDATE
SET servings = $2, prep_minutes = $3, cook_minutes = $4, ingredients = $5, steps = $6
`

type UpsertRecipeDetailParams struct {
	EntryID     int32           `json:"entry_id"`
	Servings    int32           `json:"servings"`
	PrepMinutes int32           `json:"prep_minutes"`
	CookMinutes int32           `json:"cook_minutes"`
	Ingredients json.RawMessage `json:"ingredients"`
	Steps       json.RawMessage `json:"steps"`
}

func (q *Queries) UpsertRecipeDetail(ctx context.Context, arg UpsertRecipeDetailParams) error {
	_, err := q.db.ExecContext(ctx, upsertRecipeDetail,
		arg.EntryID,
		arg.Servings,
		arg.PrepMinutes,
		arg.CookMinutes,
		arg.Ingredients,
		arg.Steps,
	)
	return err
}
